app/routes/routesData.py
from flask import Blueprint, jsonify, render_template, request, url_for, session
from ..models.models import User, Codes
from functools import wraps
try:
    from migrate.db import getResult
except ImportError as e:
    print(f"Error: Unable to import 'migrate.db'. {str(e)}")
    
bp = Blueprint('bp', __name__)

def login_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return f(*args, **kwargs)
        else:
            return render_template('login.html')
    return wrap

@bp.route('/enviar', methods=['POST'])
@login_required
def send_code():

    data = request.get_json()

    code_user = data.get('code')
    language = data.get('language')
    problem = data.get('problem')
    resultado = getResult(code_user, language, problem)
    """
    if(language == "csharp"):
        resultado = resultado.text"""

    return jsonify({"message": resultado}), 201   

@bp.route('/')
@login_required
def home():
    user_exercise = session['user']['exercise']

    cards = [
        {},
        {
            'title': 'FizzBuzz',
            'description': 'El problema de FizzBuzz consiste en reemplazar los números de una lista con "Fizz" si son múltiplos de 3, "Buzz" si son múltiplos de 5, y "FizzBuzz" si son múltiplos de ambos.',
            'image_url': url_for('static', filename='img/fizzbuzz-logo.png'),
            'stars': 3
        },
        {
            'title': 'Palindrome',
            'description': 'El algoritmo para verificar si una palabra es un palíndromo normaliza la entrada eliminando espacios y convirtiendo todas las letras a minúsculas. Luego, compara la palabra resultante con su versión invertida. Si ambas versiones son iguales, la palabra es un palíndromo; de lo contrario, no lo es.',
            'image_url': url_for('static', filename='img/palindrome-logo.png'),
            'stars': 2
        },
        {
            'title': 'BinarySearch',
            'description': 'El algoritmo de Binary Search busca un elemento en una lista ordenada dividiendo repetidamente el rango de búsqueda a la mitad, comparando el elemento buscado con el valor en el punto medio, y ajustando el rango según corresponda.',
            'image_url': url_for('static', filename='img/binary-logo.png'),
            'stars': 2
        },
        {
            'title': 'IntegerToRoman',
            'description': 'El algoritmo de Integer to Roman convierte un número entero a su representación en números romanos utilizando un enfoque de resta. Se utilizan listas de valores y símbolos romanos para formar la representación correcta a partir de la entrada numérica.',
            'image_url': url_for('static', filename='img/integerToRoman-logo.png'),
            'stars': 4
        },
        {
            'title': 'RomanToInteger',
            'description': 'El algoritmo RomanToInteger convierte números romanos a enteros, analizando los símbolos y aplicando reglas de suma y resta según su posición. Se procesa la cadena de derecha a izquierda para calcular el valor total.',
            'image_url': url_for('static', filename='img/romanToInteger-logo.png'),
            'stars': 4
        },
        {
            'title': 'MoneyToEnglish',
            'description': 'El algoritmo MoneyToEnglish convierte una cantidad monetaria en su representación textual en inglés. Descompone el número en partes enteras y decimales, convirtiendo cada una en palabras para generar una salida clara y correcta.',
            'image_url': url_for('static', filename='img/moneyToEnglish-logo.png'),
            'stars': 5
        },
        {
            'title': 'SpiralMatrix',
            'description': 'El problema de "Spiral Matrix" consiste en, dada una matriz de enteros de dimensiones m x n (donde m es el número de filas y n es el número de columnas), imprimir los elementos de la matriz en un orden espiral',
            'image_url': url_for('static', filename='img/spiral-logo.png'),
            'stars': 4
        },
        {
            'title': 'MedianOfTwoSortedArrays',
            'description': "'El problema de \"Median of Two Sorted Arrays\" consiste en, dadas dos matrices ordenadas, nums1 y nums2 de tamaño m y n respectivamente, devolver la mediana de las dos matrices ordenadas. La mediana es el valor que separa la mitad superior de la mitad inferior de los elementos cuando las dos matrices se combinan y se ordenan.'",
            'image_url': url_for('static', filename='img/median-logo.png'),
            'stars': 2
        },
        {
            'title': 'LongerValidParentheses',
            'description': "'El problema de \"Longer valid parentheses\" consiste Dada una cadena que contiene solo los caracteres '(' y ')', devuelve la longitud del paréntesis válido más largo'",
            'image_url': url_for('static', filename='img/parentheses-logo.png'),
            'stars': 3
        },
        {
            'title': 'CountofSmallerNumbersAfterSelf',
            'description': "'El problema de \"Count of Smaller Numbers After Self\" Consistes en dada una matriz con numeros enteros, se debera devolver una matriz de enteros donde sus elementos sean el numero de elemenentos mas pequeños a la derecha de nums[i]'",
            'image_url': url_for('static', filename='img/count-logo.png'),
            'stars': 1
        },

    ]

    
    for i, card in enumerate(cards):
        if i != 0:
            card['status'] = user_exercise[i-1]
    

    return render_template('index.html', cards=enumerate(cards))

@bp.route('/problems')
@login_required
def problems():
    value = request.args.get('value', default=None, type=int)
    language = request.args.get('language', default='python')
    problems = [
        {},
        { 
            'id': '0',
            'title': 'FizzBuzz',
            'problem': '<b>OBJETIVO:</b> \n\n El objetivo del ejercicio es verificar si un numero dado cumple las condiciones: \n\n Divisibilidad por 3: Si el numero es divisible por 3, devolverás "Fizz". \n\n Divisibilidad por ambos: Si el numero es divisible por 5, devolverás "Buzz". \n\n Divisibilidad por 3: Si el numero es divisible por ambos, devolveras "FizzBuzz". \n\n No es divisible ni por 3 ni por 5: Si el número no es divisible ni por 3 ni por 5, devolverás el número en forma de cadena. \n\n <b>Entrada:</b>: n: int : Un número entero (para python) o un numero long (para c#). \n\n <b>Salida:</b>: str: devuelve "Fizz", "Buzz", "FizzBuzz", o el número en forma de cadena. \n\n <b>Ejemplo:</b> \n\n <b>Entrada:</b> n = 15 \n\n <b>Salida:</b> = FizzBuzz \n\n <b>Explicacion:</b> = En este caso, 15 es divisible tanto por 3 como por 5, por lo que la salida es "FizzBuzz".\n\n<b>CONDICIONES:</b>\nNo se debe usar "if" en la solución.',
            'image_url': url_for('static', filename='img/fizzbuzz-logo.png'),
            'stars': 3,
            "languages": {
                'python': {'code': 'def fizzbuzz(n):\n\n    #ESCRIBE TU CÓDIGO AQUÍ'},
                "c#": {
                    "code": "using TritecAPI.Interfaces;\n\nnamespace TritecAPI.problem_solver\n{\n    public class FizzBuzz : IProblemSolver\n    {\n        public string _fizzBuzz(long number)\n        {\n            //ESCRIBE TU CÓDIGO AQUÍ\n        }\n    }\n}"
                },
                "java": {
                    "code": "public class FizzBuzz {\n    \n    public static String fizzBuzz(int numero) {\n            //ESCRIBE TU CÓDIGO AQUÍ\n    }\n}"
                }
            }
        },            
        {
            'id': '1',
            'title': 'Palindrome',
            'problem': '<b>OBJETIVO:</b> \n\n El objetivo es verificar si una palabra es palíndromo. Un palíndromo es una palabra que se lee igual de izquierda a derecha y de derecha a izquierda, ignorando los espacios. \n\n <b>Entrada:</b>: word: str \n\n <b>Salida:</b>: bool : True si la palabra es palindromo, False en caso contrario. \n\n <b>Ejemplo:</b> \n\n <b>Entrada:</b>: \"anita lava la tina\" \n\n <b>Salida:</b> = True \n\n <b>Explicacion:</b> = La frase \"anita lava la tina\" es un palíndromo porque se lee igual de izquierda a derecha que de derecha a izquierda, ignorando los espacios. ',
            'image_url': url_for('static', filename='img/palindrome-logo.png'),
            'stars': 2,
            'languages': {
                'python': {'code': 'def is_palindrome(word):\n\n    #ESCRIBE TU CÓDIGO AQUÍ'},
                'c#': {'code': 'using TritecAPI.Interfaces;\n\nnamespace TritecAPI.problem_solver\n{\n    public class Palindrome\n    {\n        public bool _palindrome(string word)\n        {\n            //ESCRIBE TU CÓDIGO AQUÍ\n        }\n    }\n}'},
                'java': {"code": "public class Palindrome {\n    public static boolean isPalindrome(String word) {\n        //ESCRIBE TU CÓDIGO AQUÍ\n    }\n}"}
                
            }
        },
        {
            'id': '2',
            'title': 'BinarySearch',
            'problem': '<b>OBJETIVO:</b> \n\n Realiza una busqueda binario en un arreglo ordenado para encontrar la posicion de un valor objetivo. \n\n <b>Entrada:</b>: arr (Un arreglo ordenado de elementos), target(El valor que se desea encontrar).\n\n <b>Salida:</b>: int: El indice del target en el arreglo si se encuentra. En caso contrario, se devuelve -1). \n\n <b>Ejemplo:</b> \n\n <b>Entrada:</b>: arr = [1, 3, 5, 7, 9, 11], target = 7 \n\n <b>Salida:</b> = 3 \n\n <b>Explicacion:</b> = El valor 7 se encuentra en la posicion 3 del arreglo \n\n <b>CONDICIONES:</b> \n\n Establecer los índices low, high y mid, Funcionar con un ciclo while, su respectivo retorno',           
            'image_url': url_for('static', filename='img/binary-logo.png'),
            'stars': 2,
            'languages': {
                'python': {'code': 'def binary_search(arr, target):\n\n    #ESCRIBE TU CÓDIGO AQUÍ'},

app/templates/partials/botonInit.html
<img
  class="bg-button"
  src="{{ url_for('static', filename='img/arrow.png') }}"
  alt="logoExercise"
/>

app/templates/partials/card.html
{% for index, card in cards %}
<div class="total-container flex items-center">
  <div class="mt-2">
    {% if card.status %}
    <div class="excercises-color2 mb-2 p-2 pr-4 flex items-center">
    {% else %}
    <div class="excercises-color mb-2 p-2 pr-4 flex items-center">
    {% endif %}
      <div class="flex justify-center items-center">
        <img class="image-home" src="{{ card.image_url }}" alt="{{card.title}}" />
      </div>
      <div class="container-content w-80">
        <div class="title-exercise font-bold text-1xl">
          <h3>{{card.title}}</h3>
        </div>
        <div class="content-excercise">
          <p>{{card.description}}</p>
        </div>
      </div>
      <div class="stars flex column">
        {% for _ in range(card.stars) %} 
            {% include 'partials/star.html' %} 
        {%endfor %} 

        {% for _ in range(5 - card.stars) %} 
            {% include 'partials/starNull.html' %} 
        {% endfor %}
      </div>
    </div>
  </div>

  <div class="button-init">
    <a href="{{ url_for('bp.problems', value=index) }}" class="init-btn"> {% include 'partials/botonInit.html' %} </a>
  </div>
</div>
{% endfor %}

app/templates/partials/cardUser.html
<div class="total-container2 flex items-center">
  <div class="w-full">
    <div class="p-2 flex items-center space-x-4">
      <div class="flex-shrink-0">
        <img
          class="image-user w-16 h-16 object-cover"
          src="{{ card.image_url }}"
          alt="{{ card.title }}"
        />
      </div>

      <div class="flex-1">
        <h3 class="title-exercise font-bold text-xl">{{ card.title }}</h3>
      </div>

      <div class="flex-shrink-0 flex gap-5 items-center">
        <p class="text-m text-white">{{ card.verify }}</p>
        <img class="w-12 h-12" src="{{ card.status }}" alt="{{ card.title }}" />
      </div>
    </div>
  </div>
</div>

app/templates/partials/modal.html
<div id="modal" class="modal" style="background-color: #D5F4F7;">
    <h4>Title</h4>
    <p>Buenardo, pasaste al siguiente nivel mi papacho</p>
</div>

app/templates/partials/navbar.html
<nav class="p-2 navbar-color">
  <ul class="flex space-x-4 items-center justify-between ml-2 mr-2">
    <li>
      <a href="{{ url_for('bp.home') }}">
        <img
          src="{{ url_for('static', filename='img/logo.png') }}"
          alt="logo"
          class="logo"
        />
      </a>
    </li>
    <li>
      <div class="sesionActive">
        {% if session.get('user') and session['user'].get('username') %}
        <a href="{{ url_for('bp.user') }}">
          <img src="../../static/img/user.png" alt="User" width="50px">
        </a>
        <form action="{{ url_for('bp.signout') }}" method="GET">
          <button type="submit" style="font-weight: bold;" class="btn btn-danger">Cerrar sesión</button>
        </form>
      {% endif %}
      </div>
    </li>
  </ul>
</nav>

app/templates/partials/star.html
<img src="{{ url_for('static', filename='img/star.png') }}" alt="star">

app/templates/partials/starNull.html
<img src="{{ url_for('static', filename='img/starNull.png') }}" alt="starNull">